# 論文PDFを検索するフォルダパス（絶対パスまたは相対パス）
# 複数のフォルダを指定する場合はリスト形式で記述
input_folders:
  - "./papers"
  # - "./other_papers"  # 必要に応じてコメントを外して追加

# リネームしたPDFを保存するフォルダパス（絶対パスまたは相対パス）
output_folder: "./outputs"

# 処理済みのPDFファイルの移動先フォルダ
processed_folder: "./processed_papers"
